name: "release"

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'module.json'
            prop_path: 'version'
      - run: echo ${{steps.version.outputs.prop}} 

      - name: Update module.json
        run: |
          sed -i '/"download":/c\    "download": "https://github.com/maxostarr/pathfinder-sheet-field-calculator/releases/download/${{ steps.get_version.outputs.VERSION }}/release-${{steps.version.outputs.prop}}.zip",' module.json
          cat module.json


      - name: "Create Zip"
        run: |
          zip -r release-${{steps.version.outputs.prop}}.zip . -x ./.git/**\* ./.github/**\*

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{steps.version.outputs.prop}}"
          prerelease: false
          title: "Release"
          files: |
            release-${{steps.version.outputs.prop}}.zip
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Github Workflow
          message: "Deploy Release ${{ steps.version.outputs.prop }}"
          ref: 'master'
          add: module.json docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
